apiVersion: v1
kind: Namespace
metadata:
  name: prod
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: prod
  labels:
    app: tomcat-dm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
      ver: stable
      space: prod
  template:
    metadata:
      labels:
        app: tomcat
        ver: stable
        space: prod
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.0.50-jre8-alpine
        ports:
        - name: http
          containerPort: 8080
        - name: ajp
          containerPort: 8009

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: prod
  labels:
    app: tomcat-svc
spec:
  selector:
    app: tomcat
    ver: stable
    space: prod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: prod
  labels:
    app: tomcat-ingress
spec:
  rules:
  - host: tomcat.ik8s.io
    http:
      paths:
      - path:
        backend:        
          serviceName: tomcat-service
          servicePort: 80
  

