apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
    app: clusterip
  # default is clusterip,not specified will be randomly assigned,we can access in cluster internal
  type: ClusterIP
  clusterIP: 10.96.96.96
   
  ports:
  - name: http    #can't use daxie
    protocol: TCP
    port: 30080
    targetPort: 80   # upstream pod port
  - name: https    #can't use daxie
    protocol: TCP
    port: 30443
    targetPort: 443   # upstream pod port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterip-deployment
spec:
  selector: 
    matchLabels:
      app: clusterip
  replicas: 2
  template:
    metadata:
      labels:
        app: clusterip
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
