apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: loadbalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
spec:
  selector:
    matchLabels:
      app: loadbalancer
  replicas: 2
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        
      
  
