apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: nodeport
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    # if not specified,port are randomly assigned
    nodePort: 30080
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-deployment
spec:
  selector:
    matchLabels:
      app: nodeport
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeport
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v2
        

  

