apiVersion: v1
kind: Service
metadata:
  name: externalip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demoapp
  ports:
  - name: http
    protocol: TCP
    # service port
    port: 80
    # container port
    targetPort: 80
  # only this node listen port
  externalIPs:
  - 192.168.183.131

