apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: nodeport
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    # service port
    port: 8080
    # container port
    targetPort: 80
    # if not specified,port are randomly assigned,expose node port
    nodePort: 30080
    # liuliang diaodu policy,default cluster, local liuliang zhihui zai local node chuli
  #externalTrafficPolicy: Local
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-deployment
spec:
  selector:
    matchLabels:
      app: nodeport
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeport
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v2
        

  

