apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-endpoint-service
  namespace: default
subsets:
- addresses:
  - ip: 192.168.183.130
  - ip: 192.168.183.131
  ports:
  - name: mysql
    port: 3306
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-endpoint-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP   
