apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
      #nodePort: 30093
  selector:
    k8s-app: alertmanager
  type: "ClusterIP"
  #type: "NodePort"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-alertmanager
  namespace: kube-system
spec:
  rules:
  - host: alertmanager.ik8s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager
          servicePort: 9093
