apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-01
  labels:
    release: nfs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: "/data/nfs/v1"
    server: nfs.k8s.io

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-02
  labels:
    release: nfs-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: "/data/nfs/v2"
    server: nfs.k8s.io

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-03
  labels:
    release: nfs-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: "/data/nfs/v3"
    server: nfs.k8s.io

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-04
  labels:
    release: nfs-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: "/data/nfs/v4"
    server: nfs.k8s.io

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-05
  labels:
    release: nfs-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
  nfs:
    path: "/data/nfs/v5"
    server: nfs.k8s.io
