kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    kubernetes.io/name: "Prometheus"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  #type: NodePort
  type: ClusterIP
  clusterIP: 10.96.88.88
  ports:
    - port: 9090
      name: http
      protocol: TCP
      #nodePort: 30090

#    - name: http
#      port: 9090
#      protocol: TCP
#      targetPort: 9090
  selector:
    k8s-app: prometheus

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-prometheus
  namespace: kube-system
spec:
  rules:
  - host: prometheus.ik8s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
