apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-config
  namespace: kube-system
data:
  node_exporter_key: |
    #!/bin/sh
    # for my define key
    echo Node_Procs_Zombie `ps axo pid=,stat= | grep S | wc -l`  
    echo Node_Login_Users  `who | wc -l`
