apiVersion: v1
kind: Pod
metadata:
  name: set-env-pod
spec:
  containers:
  - name: filebeat
    image: ikubernetes/filebeat:5.6.5-alpine
    env:
    - name: LOG_LEVEL
      value: warning
    - name: REDIS_HOST
      value: db.linux.io
