apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-myapp
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata:
      name: deployment-myapp-pod
      #namespace: default
      labels:
        app: myapp
        release: canary
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        ports:
        - name: http
          containerPort: 80
