apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-controller
  labels:
    controller: ds
spec:
  updateStrategy:
    rollingUpdate: 
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: ds
  template:
    metadata:
      name: filebeat
      labels:
        app: ds
    spec:
      containers:
      - name: filebeat
        image: ikubernetes/filebeat:5.6.5-alpine
        env:
        - name: REDIS_HOST
          value: db.ikubernetes.io:6379
        - name: LOG_LEVEL
          value: info
