apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-poststart-pod
  labels:
    lifecycle: start
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo 'lifecycle hooks handler' > /usr/share/nginx/html/test.html"]

      #postStart:
      #  exec:
      #    command: ["/bin/sh","-c","echo 'lifecycle hooks handler' > /usr/share/nginx/html/test.html"]
