apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcpsocket-pod
  labels:
    check: tcpsocket
spec:
  containers:
  - name: nginx
    image: nginx:1.12-alpine
    ports:
    - name: http
      containerPort: 80
    livenessProbe:
      tcpSocket:
        port: http
