apiVersion: v1
kind: Pod
metadata:
  name: readiness-exec-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh","-c","while true;do sleep 20;touch /tmp/ready;sleep 30;rm -f /tmp/ready;done"]
    
    readinessProbe:
      exec:
        command: ["test","-e","/tmp/ready"]
      initialDelaySeconds: 5
      periodSeconds: 5
