apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  #for all containers
  #securityContext:
  #  runAsNonRoot: true 
  #  runAsUser : 1000 
 
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c","sleep 86400"]

    #only for this container 
    securityContext:
      runAsNonRoot: true 
      runAsUser : 1000 
