apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-01
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=1.3.0
  nfs:
    path:  "/data/v1"
    server: node3.k8s.io

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-02
  labels:
    release: stable
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=1.3.0
  nfs:
    path:  "/data/v2"
    server: node3.k8s.io

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-03
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=1.3.0
  nfs:
    path:  "/data/v3"
    server: node3.k8s.io
