apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: default
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: web
      containerPort: 80
  nodeSelector: 
    app: myapp
    release: canary  
