apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-controller
  labels:
    controller: dm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      name: deployment-controller-pod
      labels:
        app: dm
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1 

