apiVersion: batch/v1
kind: Job
metadata:
  name: job-controller-v2
  labels:
    controller: job
spec:
  completions: 5   #all task num
  parallelism: 2   #bingxing
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: myjob
        image: alpine
        command: ["/bin/sh",  "-c", "sleep 120"]
      restartPolicy: Never
