apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
  namespace: default
spec:
  containers:
  - image: nginx:alpine
    name: nginx-server
    volumeMounts:
    - name: ngxconfs
      mountPath: /etc/nginx/conf.d/
      readOnly: true
  # 通过挂载configmap来使用
  volumes:
  - name: ngxconfs
    configMap:
      name: nginx-config-files
      optional: false
