kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-reader-rolebinding
  namespace: default
subjects:
- kind: User
  name: liuzc
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rbac-reader-role
  apiGroup: rbac.authorization.k8s.io
