kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-reader-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log"]
  verbs: ["get", "list", "watch"] 
