#apiVersion: v1
#kind: Service
#metadata:
#  name: redis-service 
#  namespace: default
#spec:
#  selector:
#    app: redis 
#    role: logstorge
#  clusterIP: 10.99.99.99
#  type: ClusterIP
#  ports:
#  - port: 6379
#    targetPort: 6379 

apiVersion: v1
kind: Service
metadata:
  name: myapp-service 
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  clusterIP: 10.98.98.98
  #clusterIP: None
  type: NodePort
  #sessionAffinity: ClientIP
  #sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80 
    nodePort: 30080
