apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-01
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: slow
  selector:
    matchLabels:
      release: stable 

---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    app: stable
spec:
  containers:
  - name: myapp
    image: ikubernetes/myspp:v1
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: pvc-nfs-01
