apiVersion: rbac.authorization.k8s.io/v1
kind: Rolebinding
metadata:
  name: reources-reader
  namespace: testing
subjects:
- kind: User
  name: kube-user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io
