apiVersion: v1
kind: Pod
metadata:
  name: readness-httpget-pod
  namespace: default
spec:
  containers:
  - name: demoapp2
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        path: '/readyz/'
        port: 80
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 3
  restartPolicy: Always
