apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-pod
  labels:
    app: nfs-volume
spec:
  nodeName: node1.k8s.io
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - name: redisport
      containerPort: 6379
    volumeMounts:
    - name: redisdata
      mountPath: /data
  volumes:
    - name: redisdata
      nfs:
        server: nfs.k8s.io
        path: /data/v1
